### ISSUE TITLE
logfile system.xml.xmlException Error

### ISSUE THREAD

**Issue by SCUR0** [jjxtra/Windows-IP-Ban-Service#33]
I've been getting this error posted in logs at random:

```
2018-02-09 18:46:02.0660|ERROR|FileLogger|System.Xml.XmlException: '', hexadecimal value 0x01, is an invalid character. Line 5, position 31.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlCharCheckingReader.Read()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at IPBan.IPBanService.ParseXml(String xml)
   at IPBan.IPBanService.ProcessXml(String xml)
   at IPBan.IPBanService.EventRecordWritten(Object sender, EventRecordWrittenEventArgs e)
```

**Comment by SCUR0** [comment]
This is not fixed. I am still getting this error at random:

```
2018-03-07 10:42:48.9290|ERROR|FileLogger|System.Xml.XmlException: '', hexadecimal value 0x01, is an invalid character. Line 5, position 31.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlCharCheckingReader.Read()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at IPBan.IPBanService.ParseXml(String xml) in C:\Users\Jeff\Documents\GitHub\Windows-IP-Ban-Service\IPBanService.cs:line 249
   at IPBan.IPBanService.ProcessXml(String xml) in C:\Users\Jeff\Documents\GitHub\Windows-IP-Ban-Service\IPBanService.cs:line 492
   at IPBan.IPBanService.EventRecordWritten(Object sender, EventRecordWrittenEventArgs e) in C:\Users\Jeff\Documents\GitHub\Windows-IP-Ban-Service\IPBanService.cs:line 516

```
