### ISSUE TITLE
Log files states errors

### ISSUE THREAD

**Issue by Lordcorvin1** [jjxtra/Windows-IP-Ban-Service#37]
`2018-04-21 22:27:39.4594|ERROR|FileLogger|Failed to create event viewer watcher: System.Diagnostics.Eventing.Reader.EventLogNotFoundException: The specified channel could not be found. Check channel configuration
   at System.Diagnostics.Eventing.Reader.EventLogException.Throw(Int32 errorCode)
   at System.Diagnostics.Eventing.Reader.NativeWrapper.EvtSubscribe(EventLogHandle session, SafeWaitHandle signalEvent, String path, String query, EventLogHandle bookmark, IntPtr context, IntPtr callback, Int32 flags)
   at System.Diagnostics.Eventing.Reader.EventLogWatcher.StartSubscribing()
   at IPBan.IPBanService.SetupEventLogWatcher() in C:\Users\Jeff\Documents\GitHub\Windows-IP-Ban-Service\IPBanService.cs:line 550`

Everything is default, using latest release.

**Comment by Lordcorvin1** [comment]
To add, I did everything that readme asks me to do.
I'm on Windows 2008 r2 if it makes a difference

**Comment by jjxtra** [comment]
Not seeing error on my machines. Does it happen on server 2012+?

**Comment by jjxtra** [comment]
You can also comment out bits of the config one by one

**Comment by Lordcorvin1** [comment]
Never tried 2012, found older version I had on PC and no errors. I'll try investigating and if I find anything I'll tell you

**Comment by rbgnr111** [comment]
I had been trying this on win 2008 R2 and am getting the same error. 

2018-05-14 21:02:15.7896|INFO|FileLogger|Started IPBan service
2018-05-14 21:02:15.8696|ERROR|FileLogger|Failed to create event viewer watcher:
 System.Diagnostics.Eventing.Reader.EventLogNotFoundException: The specified cha
nnel could not be found. Check channel configuration
   at System.Diagnostics.Eventing.Reader.EventLogException.Throw(Int32 errorCode
)
   at System.Diagnostics.Eventing.Reader.NativeWrapper.EvtSubscribe(EventLogHand
le session, SafeWaitHandle signalEvent, String path, String query, EventLogHandl
e bookmark, IntPtr context, IntPtr callback, Int32 flags)
   at System.Diagnostics.Eventing.Reader.EventLogWatcher.StartSubscribing()
   at IPBan.IPBanService.SetupEventLogWatcher() in C:\Users\Jeff\Documents\GitHu
b\Windows-IP-Ban-Service\IPBanService.cs:line 550
2018-05-14 21:02:15.8896|INFO|FileLogger|Whitelist: 127.0.0.1,::1,0.0.0.0,-, Whi
telist Regex:
2018-05-14 21:02:15.8896|INFO|FileLogger|Blacklist: , Blacklist Regex:
Press ENTER to quit

**Comment by jjxtra** [comment]
Try commenting out configuration items one by one until error goes away

-- Jeff

**Comment by jjxtra** [comment]
Ok, not sure what else to try at this point. Feel free to post back if you find anything.

**Comment by andeeh** [comment]
Same error here on 2008 R2, not sure what to do next...

**Comment by jjxtra** [comment]
To comment out config entries, wrap them in 

Only do this around <Group>...</Group> elements.

Do this one by one until the error goes away and let me know which group has the problem.

**Comment by jjxtra** [comment]
No, just leave it commented out for now. Will have to figure out how to handle this case better in the future.

**Comment by andeeh** [comment]
Looks like someone posted about this here:  https://social.technet.microsoft.com/Forums/windowsserver/en-US/71c94bcf-51e6-4fbd-9a44-f2edfce34171/cannot-find-remotedesktopservicesrdpcoretsoperational-logs-event?forum=winserverTS

Apparently the path "Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational" doesn't exist in Windows Server 2008 R2?  I checked myself and it wasn't there.

**Comment by jjxtra** [comment]
Ok will add a condition for 2012+ for that somehow I guess... thanks for looking into it.
